alias sc='script/console'
alias sg='script/generate'
alias sd='script/destroy'

alias be='bundle exec'
alias resetdb='bundle exec rails db:drop db:create db:migrate db:seed'
alias ff='bundle exec rspec --fail-fast'
alias cwip='bundle exec rails cucumber:wip'
alias spec='bundle exec rspec spec'
alias rrg='bundle exec rails routes | grep'
alias bers='bundle exec rails s'
alias brcu='bundle exec rails cucumber'
alias rgm='bundle exec rails g migration'
alias rdbm='bundle exec rails db:migrate'
alias rdbr='bundle exec rails db:rollback'
alias beg='bundle exec guard'
alias brc='bundle exec rails c'
